# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:10.6-postgis
        environment:
          POSTGRES_USER: osm
          POSTGRES_DB: osm

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn install

      # Send code coverage report
      - run: mvn test -P integration
      - run: "bash <(curl -s https://codecov.io/bash)"

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
