layers:
  - name: 'aeroway'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'aeroway'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'aeroway'
  - name: 'waterway'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'waterway'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'waterway'
      UNION
      SELECT id, tags, geom
      FROM osm_relations
      WHERE tags ? 'waterway'
      AND tags -> 'type' = 'multipolygon'
  - name: 'landuse'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'landuse'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'landuse'
      UNION
      SELECT id, tags, geom
      FROM osm_relations
      WHERE tags ? 'landuse'
      AND tags -> 'type' = 'multipolygon'
  - name: 'railway'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'railway'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'railway'
  - name: 'highway'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'highway'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'highway'
  - name: 'geological'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'geological'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'geological'
  # Zoom 12 to 14
  - name: 'public_transport'
    minZoom: 12
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'public_transport'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'public_transport'
  - name: 'aerialway'
    minZoom: 12
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'aerialway'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'aerialway'
  - name: 'geological'
    minZoom: 12
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'barrier'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'barrier'
  - name: 'building'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT w.id, w.tags, w.geom
      FROM osm_ways AS w
      WHERE w.tags -> 'building' = 'yes'
      UNION
      SELECT id, tags, geom
      FROM osm_relations
      WHERE tags -> 'building' = 'yes'
  - name: 'amenity'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'amenity'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'amenity'
  - name: 'craft'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'craft'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'craft'
  - name: 'emergency'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'emergency'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'emergency'
  - name: 'historic'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'historic'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'historic'
  - name: 'leisure'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'leisure'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'leisure'
  - name: 'man_made'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'man_made'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'man_made'
  - name: 'military'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'military'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'military'
  - name: 'natural'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'natural'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'natural'
      UNION
      SELECT id, tags, geom
      FROM osm_relations
      WHERE tags ? 'natural'
      AND tags -> 'type' = 'multipolygon'
  - name: 'office'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'office'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'office'
  - name: 'place'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'place'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'place'
  - name: 'power'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'power'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'power'
  - name: 'route'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'route'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'route'
  - name: 'shop'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'shop'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'shop'
  - name: 'sport'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'sport'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'sport'
  - name: 'telecom'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'telecom'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'telecom'
  - name: 'tourism'
    minZoom: 14
    maxZoom: 14
    sql: >
      SELECT id, tags, geom
      FROM osm_nodes
      WHERE tags ? 'tourism'
      UNION
      SELECT id, tags, geom
      FROM osm_ways
      WHERE tags ? 'tourism'

