layers:
  - name: "buildings"
    geometry: "geom"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb, geom
      FROM ways
      WHERE tags -> 'building' = 'yes'
  - name: "highways"
    geometry: "geom"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb, geom
      FROM ways
      WHERE tags -> 'highway' = 'path'
  - name: "waterareas"
    geometry: "geom"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb, geom
      FROM ways
      WHERE tags -> 'natural' = 'water'