layers:
  - name: "buildings"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT ST_AsMVT(q, 'buildings', 4096, 'geom')
      FROM (
        SELECT id, ST_AsMvtGeom(geom, ST_MakeEnvelope({0}, {1}, {2}, {3}), 4096, 256, true) AS geom
        FROM ways
        WHERE tags -> 'building' = 'yes'
        AND geom && ST_MakeEnvelope({0}, {1}, {2}, {3})
        AND ST_Intersects(geom, ST_MakeEnvelope({0}, {1}, {2}, {3}))
      ) AS q;
  - name: "highways"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT ST_AsMVT(q, 'highways', 4096, 'geom')
      FROM (
        SELECT id, ST_AsMvtGeom(geom, ST_MakeEnvelope({0}, {1}, {2}, {3}), 4096, 256, true) AS geom
        FROM ways
        WHERE tags -> 'highway' = 'path'
        AND geom && ST_MakeEnvelope({0}, {1}, {2}, {3})
        AND ST_Intersects(geom, ST_MakeEnvelope({0}, {1}, {2}, {3}))
      ) AS q;