layers:
  - name: "buildings"
    geometry: "geom"
    minZoom: 14
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb as properties, geom as geometry
      FROM osm_ways
      WHERE tags -> 'building' = 'yes'
  - name: "highways"
    geometry: "geom"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb as properties, geom as geometry
      FROM osm_ways
      WHERE tags ? 'highway'
  - name: "waterways"
    geometry: "geom"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb as properties, geom as geometry
      FROM osm_ways
      WHERE tags ? 'waterway'
  - name: "waterareas"
    geometry: "geom"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb as properties, geom as geometry
      FROM osm_ways
      WHERE tags -> 'natural' = 'water'
      UNION
      SELECT id, tags::jsonb as properties, geom as geometry
      FROM osm_relations
      WHERE tags -> 'natural' = 'water'
  - name: "forests"
    geometry: "geom"
    minZoom: 0
    maxZoom: 18
    sql: >
      SELECT id, tags::jsonb as properties, geom as geometry
      FROM osm_relations
      WHERE tags -> 'type' = 'multipolygon' AND tags -> 'landuse' = 'forest'
