id: 'contour'
lon: 9.5554
lat: 47.1660
zoom: 14
minZoom: 12
maxZoom: 19
layers:
  - id: 'aster_dem'
    type: 'geometry'
    minZoom: 12
    maxZoom: 20
    queries:
      - SELECT id, hstore('elevation', elevation::text) as tags, wkb_geometry as geom FROM aster_dem
