name: Build

on: [push]

jobs:

  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Postgis 11
        uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql password: ${{ secrets.POSTGRESQL_PASSWORD }}
          postgresql user: 'baremaps'
          postgresql db: 'baremaps'
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -P integration -B package --file pom.xml
      - name: Upload code coverage
        run: bash <(curl -s https://codecov.io/bash)

  build-macos:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml

